### ISSUE TITLE
Add a Chocolatey repo link badge for software pages

### ISSUE THREAD

**Issue by Ma3yTa** [chocolatey/chocolatey-media-kit#1]
please add some badges as https://snapcraft.io/ has, examples:

[![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-black.svg)](https://snapcraft.io/fman)

[![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-white.svg)](https://snapcraft.io/fman)

It can be something like:

[<img src="https://i.gyazo.com/543ea404ce6f062ddf8e0e26774be037.png" alt="drawing" height="56"/>
](https://chocolatey.org/packages/fman/1.5.7.0)

**Comment by ferventcoder** [comment]
This has been moved over to the media kit repo (just created). We'll put the rest of the media kit that is shareable into here as well.

**Comment by designxsteph** [comment]
@gep13 @ferventcoder @Ma3yTa What about something like this? Wasn't sure what exactly the "Get it from" makes sense or if it should say something else.

Light:

![chocolatey-badge-light](https://user-images.githubusercontent.com/42750725/57097351-24a6e380-6cdd-11e9-9da9-0a2301f6f971.png)

Dark:

![chocolatey-badge-dark](https://user-images.githubusercontent.com/42750725/57097373-34bec300-6cdd-11e9-83f8-8edb99b9e337.png)
